package com.highway.etc.common;

import java.io.Serializable;
import java.time.Instant;

/**
 * Plate-clone anomaly generated by {@code PlateCloneDetectionJob}.
 */
public class Alert implements Serializable {

    private static final long serialVersionUID = 1L;

    public String hphmMask;
    /**
     * Sharding key for alert_plate_clone, use earlier station to keep routing
     * stable.
     */
    public int stationId;
    public int firstStationId;
    public int secondStationId;
    public long timeGapSec;
    public double distanceKm;
    public double speedKmh;
    public double confidence;
    public Instant generatedAt;

    public static Alert of(int shardStationId, String plateMask, int firstId, int secondId,
            long gapSec, double distanceKm, double speedKmh, double confidence) {
        Alert a = new Alert();
        a.stationId = shardStationId;
        a.hphmMask = plateMask;
        a.firstStationId = firstId;
        a.secondStationId = secondId;
        a.timeGapSec = gapSec;
        a.distanceKm = distanceKm;
        a.speedKmh = speedKmh;
        a.confidence = confidence;
        a.generatedAt = Instant.now();
        return a;
    }

    @Override
    public String toString() {
        return "Alert{"
                + "hphmMask='" + hphmMask + '\''
                + ", firstStationId=" + firstStationId
                + ", secondStationId=" + secondStationId
                + ", timeGapSec=" + timeGapSec
                + ", distanceKm=" + distanceKm
                + ", speedKmh=" + speedKmh
                + ", confidence=" + confidence
                + ", generatedAt=" + generatedAt
                + '}';
    }
}
